-- Drop tables if they already exist (for re-runs)
begin
   execute immediate 'DROP TABLE reviews CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE banks CASCADE CONSTRAINTS';
exception
   when others then
      if sqlcode != -942 then
         raise;
      end if;
end;
/
-- Create Banks table
create table banks (
   id   number
      generated by default as identity
   primary key,
   name varchar2(255) not null unique
);

-- Create Reviews table
create table reviews (
   id          number
      generated by default as identity
   primary key,
   bank_id     number not null
      references banks ( id ),
   rating      number(2,1) not null,
   review_text clob,
   review_date date not null,
   source      varchar2(100) not null
);